# Generated by Django 4.2.6 on 2024-04-14 11:29

import board_varification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_varification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitinspection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=board_varification.models.UploadToPathAndRename('kit_inspection_photos')),
        ),
    ]
